{
 "title": "System Final Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Frontend Avg response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "service": "frontend-service" }
   ]
  },
  {
   "title": "Backend Avg Response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "service": "backend-service" }
   ]
  },
  {
   "title": "System Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{pod=\"frontend-app-7446b76d8b-pwd4t\"}[$__rate_interval])",
     "legendFormat": "Frontend"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=\"backend-app-7988dfb8c-qhrlm\"}[$__rate_interval])",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Application Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container=\"backend\"})",
     "legendFormat": "backend"
    },
    {
     "expr": "avg(container_memory_usage_bytes{container=\"frontend\"})",
     "legendFormat": "frontend"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "targets": [
    {
     "expr": "avg(container_cpu_usage_seconds_total{container=\"backend\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "avg(container_cpu_usage_seconds_total{container=\"frontend\"})",
     "legendFormat": "Frontend"
    }
   ]
  }
 ]
}